# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Unity-based Simulation of Active Transport in Built Environment
author: Dimitrios Dimitriadis, Thodoris Gounelas
copyright: "2024"  # Copyright year to be placed in the footer
#logo: logo-wide.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# NOTE: commented options below have been move to sphinx section
#---------------------------------------------------------------
# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: false
#  use_repository_button: false
#  use_download_button: false
#
#launch_buttons:
#  colab_url: "https://colab.research.google.com"
#  binderhub_url: "https://mybinder.org"

parse:
  myst_enable_extensions:
    - dollarmath  # First 4 extension are active by default, but have to explictly activated when adding deflist
    - linkify
    - substitution
    - colon_fence
    - deflist # not active by default, necessary to support definition lists

sphinx:
  config:
    jblatex_captions_to_parts: false
    html_theme_options:
        use_download_button: false
        repository_url: https://github.com/onoufrios/numan
        repository_branch: main
        use_issues_button: false
        use_repository_button: false
        use_edit_page_button: false

